apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yurt-app-manager.fullname" . }}
  labels:
    {{- include "yurt-app-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yurt-app-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yurt-app-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "yurt-app-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --enable-leader-election
            - --v=4
          ports:
            - name: webhook-server
              containerPort: {{ .Values.admissionWebhooks.service.port }}
              protocol: TCP
            - name: health
              containerPort: 8000
              protocol: TCP
          env:
            - name: WEBHOOK_PORT
              value: {{ .Values.admissionWebhooks.service.port | quote }}
            - name: SECRET_NAME
              value: {{ include "yurt-app-manager.fullname" . | quote }}
            - name: SERVICE_NAME
              value: {{ include "yurt-app-manager.fullname" . | quote }}
            - name: MUTATING_WEBHOOK_CONFIGURATION_NAME
              value: {{ include "yurt-app-manager.fullname" . | quote }}
            - name: VALIDATING_WEBHOOK_CONFIGURATION_NAME
              value: {{ include "yurt-app-manager.fullname" . | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEBHOOK_CERT_DIR
              value: {{ .Values.admissionWebhooks.certificate.mountPath | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: {{ .Values.admissionWebhooks.certificate.mountPath }}
              name: cert
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ template "yurt-app-manager.fullname" . }}-admission
