apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yurt-app-manager.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yurt-app-manager.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yurt-app-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}