apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "yurt-app-manager.fullname" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "yurt-app-manager.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
      path: /validate-apps-openyurt-io-v1alpha1-nodepool
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vnodepool.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - nodepools
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "yurt-app-manager.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
      path: /validate-apps-openyurt-io-v1alpha1-uniteddeployment
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vuniteddeployment.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uniteddeployments
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "yurt-app-manager.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
      path: /validate-apps-openyurt-io-v1alpha1-yurtappdaemon
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vyurtappdaemon.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - yurtappdaemons
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "yurt-app-manager.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
      path: /validate-apps-openyurt-io-v1alpha1-yurtingress
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vyurtingress.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - yurtingresses