# permissions for end users to edit yurtingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yurtingress-editor-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - yurtingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - yurtingresses/status
  verbs:
  - get
