/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeYurtAppSets implements YurtAppSetInterface
type FakeYurtAppSets struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var yurtappsetsResource = schema.GroupVersionResource{Group: "apps.openyurt.io", Version: "v1alpha1", Resource: "yurtappsets"}

var yurtappsetsKind = schema.GroupVersionKind{Group: "apps.openyurt.io", Version: "v1alpha1", Kind: "YurtAppSet"}

// Get takes name of the yurtAppSet, and returns the corresponding yurtAppSet object, and an error if there is any.
func (c *FakeYurtAppSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.YurtAppSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(yurtappsetsResource, c.ns, name), &v1alpha1.YurtAppSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppSet), err
}

// List takes label and field selectors, and returns the list of YurtAppSets that match those selectors.
func (c *FakeYurtAppSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.YurtAppSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(yurtappsetsResource, yurtappsetsKind, c.ns, opts), &v1alpha1.YurtAppSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.YurtAppSetList{ListMeta: obj.(*v1alpha1.YurtAppSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.YurtAppSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested yurtAppSets.
func (c *FakeYurtAppSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(yurtappsetsResource, c.ns, opts))

}

// Create takes the representation of a yurtAppSet and creates it.  Returns the server's representation of the yurtAppSet, and an error, if there is any.
func (c *FakeYurtAppSets) Create(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.CreateOptions) (result *v1alpha1.YurtAppSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(yurtappsetsResource, c.ns, yurtAppSet), &v1alpha1.YurtAppSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppSet), err
}

// Update takes the representation of a yurtAppSet and updates it. Returns the server's representation of the yurtAppSet, and an error, if there is any.
func (c *FakeYurtAppSets) Update(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.UpdateOptions) (result *v1alpha1.YurtAppSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(yurtappsetsResource, c.ns, yurtAppSet), &v1alpha1.YurtAppSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeYurtAppSets) UpdateStatus(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.UpdateOptions) (*v1alpha1.YurtAppSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(yurtappsetsResource, "status", c.ns, yurtAppSet), &v1alpha1.YurtAppSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppSet), err
}

// Delete takes name of the yurtAppSet and deletes it. Returns an error if one occurs.
func (c *FakeYurtAppSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(yurtappsetsResource, c.ns, name), &v1alpha1.YurtAppSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeYurtAppSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(yurtappsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.YurtAppSetList{})
	return err
}

// Patch applies the patch and returns the patched yurtAppSet.
func (c *FakeYurtAppSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YurtAppSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(yurtappsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.YurtAppSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppSet), err
}
