/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUnitedDaemonSets implements UnitedDaemonSetInterface
type FakeUnitedDaemonSets struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var uniteddaemonsetsResource = schema.GroupVersionResource{Group: "apps.openyurt.io", Version: "v1alpha1", Resource: "uniteddaemonsets"}

var uniteddaemonsetsKind = schema.GroupVersionKind{Group: "apps.openyurt.io", Version: "v1alpha1", Kind: "UnitedDaemonSet"}

// Get takes name of the unitedDaemonSet, and returns the corresponding unitedDaemonSet object, and an error if there is any.
func (c *FakeUnitedDaemonSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UnitedDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(uniteddaemonsetsResource, c.ns, name), &v1alpha1.UnitedDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UnitedDaemonSet), err
}

// List takes label and field selectors, and returns the list of UnitedDaemonSets that match those selectors.
func (c *FakeUnitedDaemonSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UnitedDaemonSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(uniteddaemonsetsResource, uniteddaemonsetsKind, c.ns, opts), &v1alpha1.UnitedDaemonSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UnitedDaemonSetList{ListMeta: obj.(*v1alpha1.UnitedDaemonSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.UnitedDaemonSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested unitedDaemonSets.
func (c *FakeUnitedDaemonSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(uniteddaemonsetsResource, c.ns, opts))

}

// Create takes the representation of a unitedDaemonSet and creates it.  Returns the server's representation of the unitedDaemonSet, and an error, if there is any.
func (c *FakeUnitedDaemonSets) Create(ctx context.Context, unitedDaemonSet *v1alpha1.UnitedDaemonSet, opts v1.CreateOptions) (result *v1alpha1.UnitedDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(uniteddaemonsetsResource, c.ns, unitedDaemonSet), &v1alpha1.UnitedDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UnitedDaemonSet), err
}

// Update takes the representation of a unitedDaemonSet and updates it. Returns the server's representation of the unitedDaemonSet, and an error, if there is any.
func (c *FakeUnitedDaemonSets) Update(ctx context.Context, unitedDaemonSet *v1alpha1.UnitedDaemonSet, opts v1.UpdateOptions) (result *v1alpha1.UnitedDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(uniteddaemonsetsResource, c.ns, unitedDaemonSet), &v1alpha1.UnitedDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UnitedDaemonSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUnitedDaemonSets) UpdateStatus(ctx context.Context, unitedDaemonSet *v1alpha1.UnitedDaemonSet, opts v1.UpdateOptions) (*v1alpha1.UnitedDaemonSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(uniteddaemonsetsResource, "status", c.ns, unitedDaemonSet), &v1alpha1.UnitedDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UnitedDaemonSet), err
}

// Delete takes name of the unitedDaemonSet and deletes it. Returns an error if one occurs.
func (c *FakeUnitedDaemonSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(uniteddaemonsetsResource, c.ns, name), &v1alpha1.UnitedDaemonSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUnitedDaemonSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(uniteddaemonsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UnitedDaemonSetList{})
	return err
}

// Patch applies the patch and returns the patched unitedDaemonSet.
func (c *FakeUnitedDaemonSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UnitedDaemonSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(uniteddaemonsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.UnitedDaemonSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UnitedDaemonSet), err
}
