/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeYurtAppDaemons implements YurtAppDaemonInterface
type FakeYurtAppDaemons struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var yurtappdaemonsResource = schema.GroupVersionResource{Group: "apps.openyurt.io", Version: "v1alpha1", Resource: "yurtappdaemons"}

var yurtappdaemonsKind = schema.GroupVersionKind{Group: "apps.openyurt.io", Version: "v1alpha1", Kind: "YurtAppDaemon"}

// Get takes name of the yurtAppDaemon, and returns the corresponding yurtAppDaemon object, and an error if there is any.
func (c *FakeYurtAppDaemons) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.YurtAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(yurtappdaemonsResource, c.ns, name), &v1alpha1.YurtAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppDaemon), err
}

// List takes label and field selectors, and returns the list of YurtAppDaemons that match those selectors.
func (c *FakeYurtAppDaemons) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.YurtAppDaemonList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(yurtappdaemonsResource, yurtappdaemonsKind, c.ns, opts), &v1alpha1.YurtAppDaemonList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.YurtAppDaemonList{ListMeta: obj.(*v1alpha1.YurtAppDaemonList).ListMeta}
	for _, item := range obj.(*v1alpha1.YurtAppDaemonList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested yurtAppDaemons.
func (c *FakeYurtAppDaemons) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(yurtappdaemonsResource, c.ns, opts))

}

// Create takes the representation of a yurtAppDaemon and creates it.  Returns the server's representation of the yurtAppDaemon, and an error, if there is any.
func (c *FakeYurtAppDaemons) Create(ctx context.Context, yurtAppDaemon *v1alpha1.YurtAppDaemon, opts v1.CreateOptions) (result *v1alpha1.YurtAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(yurtappdaemonsResource, c.ns, yurtAppDaemon), &v1alpha1.YurtAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppDaemon), err
}

// Update takes the representation of a yurtAppDaemon and updates it. Returns the server's representation of the yurtAppDaemon, and an error, if there is any.
func (c *FakeYurtAppDaemons) Update(ctx context.Context, yurtAppDaemon *v1alpha1.YurtAppDaemon, opts v1.UpdateOptions) (result *v1alpha1.YurtAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(yurtappdaemonsResource, c.ns, yurtAppDaemon), &v1alpha1.YurtAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppDaemon), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeYurtAppDaemons) UpdateStatus(ctx context.Context, yurtAppDaemon *v1alpha1.YurtAppDaemon, opts v1.UpdateOptions) (*v1alpha1.YurtAppDaemon, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(yurtappdaemonsResource, "status", c.ns, yurtAppDaemon), &v1alpha1.YurtAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppDaemon), err
}

// Delete takes name of the yurtAppDaemon and deletes it. Returns an error if one occurs.
func (c *FakeYurtAppDaemons) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(yurtappdaemonsResource, c.ns, name), &v1alpha1.YurtAppDaemon{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeYurtAppDaemons) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(yurtappdaemonsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.YurtAppDaemonList{})
	return err
}

// Patch applies the patch and returns the patched yurtAppDaemon.
func (c *FakeYurtAppDaemons) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YurtAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(yurtappdaemonsResource, c.ns, name, pt, data, subresources...), &v1alpha1.YurtAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtAppDaemon), err
}
