/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeYurtIngresses implements YurtIngressInterface
type FakeYurtIngresses struct {
	Fake *FakeAppsV1alpha1
}

var yurtingressesResource = schema.GroupVersionResource{Group: "apps.openyurt.io", Version: "v1alpha1", Resource: "yurtingresses"}

var yurtingressesKind = schema.GroupVersionKind{Group: "apps.openyurt.io", Version: "v1alpha1", Kind: "YurtIngress"}

// Get takes name of the yurtIngress, and returns the corresponding yurtIngress object, and an error if there is any.
func (c *FakeYurtIngresses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.YurtIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(yurtingressesResource, name), &v1alpha1.YurtIngress{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtIngress), err
}

// List takes label and field selectors, and returns the list of YurtIngresses that match those selectors.
func (c *FakeYurtIngresses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.YurtIngressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(yurtingressesResource, yurtingressesKind, opts), &v1alpha1.YurtIngressList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.YurtIngressList{ListMeta: obj.(*v1alpha1.YurtIngressList).ListMeta}
	for _, item := range obj.(*v1alpha1.YurtIngressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested yurtIngresses.
func (c *FakeYurtIngresses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(yurtingressesResource, opts))
}

// Create takes the representation of a yurtIngress and creates it.  Returns the server's representation of the yurtIngress, and an error, if there is any.
func (c *FakeYurtIngresses) Create(ctx context.Context, yurtIngress *v1alpha1.YurtIngress, opts v1.CreateOptions) (result *v1alpha1.YurtIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(yurtingressesResource, yurtIngress), &v1alpha1.YurtIngress{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtIngress), err
}

// Update takes the representation of a yurtIngress and updates it. Returns the server's representation of the yurtIngress, and an error, if there is any.
func (c *FakeYurtIngresses) Update(ctx context.Context, yurtIngress *v1alpha1.YurtIngress, opts v1.UpdateOptions) (result *v1alpha1.YurtIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(yurtingressesResource, yurtIngress), &v1alpha1.YurtIngress{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtIngress), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeYurtIngresses) UpdateStatus(ctx context.Context, yurtIngress *v1alpha1.YurtIngress, opts v1.UpdateOptions) (*v1alpha1.YurtIngress, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(yurtingressesResource, "status", yurtIngress), &v1alpha1.YurtIngress{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtIngress), err
}

// Delete takes name of the yurtIngress and deletes it. Returns an error if one occurs.
func (c *FakeYurtIngresses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(yurtingressesResource, name), &v1alpha1.YurtIngress{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeYurtIngresses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(yurtingressesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.YurtIngressList{})
	return err
}

// Patch applies the patch and returns the patched yurtIngress.
func (c *FakeYurtIngresses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YurtIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(yurtingressesResource, name, pt, data, subresources...), &v1alpha1.YurtIngress{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YurtIngress), err
}
