/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodePools implements NodePoolInterface
type FakeNodePools struct {
	Fake *FakeAppsV1alpha1
}

var nodepoolsResource = schema.GroupVersionResource{Group: "apps.openyurt.io", Version: "v1alpha1", Resource: "nodepools"}

var nodepoolsKind = schema.GroupVersionKind{Group: "apps.openyurt.io", Version: "v1alpha1", Kind: "NodePool"}

// Get takes name of the nodePool, and returns the corresponding nodePool object, and an error if there is any.
func (c *FakeNodePools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodepoolsResource, name), &v1alpha1.NodePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePool), err
}

// List takes label and field selectors, and returns the list of NodePools that match those selectors.
func (c *FakeNodePools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nodepoolsResource, nodepoolsKind, opts), &v1alpha1.NodePoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodePoolList{ListMeta: obj.(*v1alpha1.NodePoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodePools.
func (c *FakeNodePools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nodepoolsResource, opts))
}

// Create takes the representation of a nodePool and creates it.  Returns the server's representation of the nodePool, and an error, if there is any.
func (c *FakeNodePools) Create(ctx context.Context, nodePool *v1alpha1.NodePool, opts v1.CreateOptions) (result *v1alpha1.NodePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nodepoolsResource, nodePool), &v1alpha1.NodePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePool), err
}

// Update takes the representation of a nodePool and updates it. Returns the server's representation of the nodePool, and an error, if there is any.
func (c *FakeNodePools) Update(ctx context.Context, nodePool *v1alpha1.NodePool, opts v1.UpdateOptions) (result *v1alpha1.NodePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nodepoolsResource, nodePool), &v1alpha1.NodePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodePools) UpdateStatus(ctx context.Context, nodePool *v1alpha1.NodePool, opts v1.UpdateOptions) (*v1alpha1.NodePool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(nodepoolsResource, "status", nodePool), &v1alpha1.NodePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePool), err
}

// Delete takes name of the nodePool and deletes it. Returns an error if one occurs.
func (c *FakeNodePools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(nodepoolsResource, name), &v1alpha1.NodePool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodePools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nodepoolsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodePoolList{})
	return err
}

// Patch applies the patch and returns the patched nodePool.
func (c *FakeNodePools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodepoolsResource, name, pt, data, subresources...), &v1alpha1.NodePool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePool), err
}
