/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	scheme "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// YurtAppSetsGetter has a method to return a YurtAppSetInterface.
// A group's client should implement this interface.
type YurtAppSetsGetter interface {
	YurtAppSets(namespace string) YurtAppSetInterface
}

// YurtAppSetInterface has methods to work with YurtAppSet resources.
type YurtAppSetInterface interface {
	Create(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.CreateOptions) (*v1alpha1.YurtAppSet, error)
	Update(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.UpdateOptions) (*v1alpha1.YurtAppSet, error)
	UpdateStatus(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.UpdateOptions) (*v1alpha1.YurtAppSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.YurtAppSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.YurtAppSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YurtAppSet, err error)
	YurtAppSetExpansion
}

// yurtAppSets implements YurtAppSetInterface
type yurtAppSets struct {
	client rest.Interface
	ns     string
}

// newYurtAppSets returns a YurtAppSets
func newYurtAppSets(c *AppsV1alpha1Client, namespace string) *yurtAppSets {
	return &yurtAppSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the yurtAppSet, and returns the corresponding yurtAppSet object, and an error if there is any.
func (c *yurtAppSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.YurtAppSet, err error) {
	result = &v1alpha1.YurtAppSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("yurtappsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of YurtAppSets that match those selectors.
func (c *yurtAppSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.YurtAppSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.YurtAppSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("yurtappsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested yurtAppSets.
func (c *yurtAppSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("yurtappsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a yurtAppSet and creates it.  Returns the server's representation of the yurtAppSet, and an error, if there is any.
func (c *yurtAppSets) Create(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.CreateOptions) (result *v1alpha1.YurtAppSet, err error) {
	result = &v1alpha1.YurtAppSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("yurtappsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(yurtAppSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a yurtAppSet and updates it. Returns the server's representation of the yurtAppSet, and an error, if there is any.
func (c *yurtAppSets) Update(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.UpdateOptions) (result *v1alpha1.YurtAppSet, err error) {
	result = &v1alpha1.YurtAppSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("yurtappsets").
		Name(yurtAppSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(yurtAppSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *yurtAppSets) UpdateStatus(ctx context.Context, yurtAppSet *v1alpha1.YurtAppSet, opts v1.UpdateOptions) (result *v1alpha1.YurtAppSet, err error) {
	result = &v1alpha1.YurtAppSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("yurtappsets").
		Name(yurtAppSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(yurtAppSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the yurtAppSet and deletes it. Returns an error if one occurs.
func (c *yurtAppSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("yurtappsets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *yurtAppSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("yurtappsets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched yurtAppSet.
func (c *yurtAppSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YurtAppSet, err error) {
	result = &v1alpha1.YurtAppSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("yurtappsets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
