/*
Copyright 2020 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	appsv1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/apis/apps/v1alpha1"
	versioned "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/client/clientset/versioned"
	internalinterfaces "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/client/listers/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// YurtAppSetInformer provides access to a shared informer and lister for
// YurtAppSets.
type YurtAppSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.YurtAppSetLister
}

type yurtAppSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewYurtAppSetInformer constructs a new informer for YurtAppSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewYurtAppSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredYurtAppSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredYurtAppSetInformer constructs a new informer for YurtAppSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredYurtAppSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().YurtAppSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().YurtAppSets(namespace).Watch(context.TODO(), options)
			},
		},
		&appsv1alpha1.YurtAppSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *yurtAppSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredYurtAppSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *yurtAppSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&appsv1alpha1.YurtAppSet{}, f.defaultInformer)
}

func (f *yurtAppSetInformer) Lister() v1alpha1.YurtAppSetLister {
	return v1alpha1.NewYurtAppSetLister(f.Informer().GetIndexer())
}
