name: Backport
on:
  pull_request_target:
    types:
      - closed

jobs:
  # align with kubevela's choice https://github.com/oam-dev/kubevela/blob/master/.github/workflows/back-port.yaml
  open-pr:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Open Backport PR
        uses: zeebe-io/backport-action@v0.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_workspace: ${{ github.workspace }}