name: E2E Test

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - release-*

env:
  # Common versions
  GO_VERSION: '1.16'
  GOLANGCI_VERSION: 'v1.31'
  KIND_VERSION: 'v0.7.0'
  KIND_IMAGE_VERSION: '[\"v1.20.7\"]'
  KIND_IMAGE_VERSIONS: '[\"v1.18.20\",\"v1.20.7\"]'
  KIND_CLUSTER_NAME: 'kind'

jobs:

  detect-noop:
    runs-on: ubuntu-20.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v3.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  set-k8s-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-k8s-matrix.outputs.matrix }}
    steps:
      - id: set-k8s-matrix
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "pushing tag: ${{ github.ref_name }}"
            echo "::set-output name=matrix::${{ env.KIND_IMAGE_VERSIONS }}"
          else
            echo "::set-output name=matrix::${{ env.KIND_IMAGE_VERSION }}"
          fi

  e2e-tests:
    runs-on: ubuntu-20.04
    needs: [ detect-noop,set-k8s-matrix ]
    if: needs.detect-noop.outputs.noop != 'true'
    strategy:
      matrix:
        k8s-version: ${{ fromJson(needs.set-k8s-matrix.outputs.matrix) }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
          config: ./test/kind-conf.yaml
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}

      - name: Label Cluster Node
        run: |
          kubectl get nodes --show-labels
          kubectl label node kind-control-plane openyurt.io/is-edge-worker=false

      - name: Load Image to kind cluster
        run: make kind-load

      - name: Build e2e tests
        run: make e2e-build

      - name: Run e2e tests
        run: make e2e-test

#      - name: Upload coverage report
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: /tmp/e2e-profile.out
#          flags: e2etests
#          name: codecov-umbrella
#
#      - name: Clean e2e profile
#        run: rm /tmp/e2e-profile.out
