name: sync-api
on:
  push:
    paths:
      - 'pkg/yurtappmanager/apis/**'
      - 'pkg/yurtappmanager/client/**'
    tags:
      - "v*"

jobs:
  sync-core-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        env:
          GO_VERSION: '1.16'
          GOLANGCI_VERSION: 'v1.45'
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Sync to yurt-app-manager-api Repo
        env:
          SSH_DEPLOY_KEY: ${{ secrets.OPENYURT_API_DEPLOY }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          TAG: ${{ steps.get_version.outputs.TAG }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          bash ./hack/lib/sync-api.sh
